### ISSUE TITLE
Darksky key

### ISSUE THREAD

**Issue by Harshakvarma** [jarretmoses/react-native-redux-example#1]
Awesome thanks for sharing the code I learned a lot, but please don't share the darksky keys openly it only free 1000 calls.
I just got access by pasting it into google 
https://api.darksky.net/forecast/2dbb276732a6602ce1de6bcb4bce61d8/40.680925,-73.974663

Sorry for raising a issue

**Comment by jarretmoses** [comment]
@Harshakvarma, yes definitely should not be in there. Thanks

**Comment by jarretmoses** [comment]
Resolved
